### ISSUE TITLE
API endpoint changed

### ISSUE THREAD

**Issue by Ragnnn** [orahul1/angular-weather-widget#4]
Hey mate,

I'd like to use your widget in a personal project as bonus, just saw that it doesn't work as the API endpoint has been changed from "api.apixu.com" to "api.weatherstack.com"

Have a great day!

**Comment by abhinavkk** [comment]
Hey!

Can you publish this update in the npm registry!

**Comment by orahul1** [comment]
I Will update this weekend.

**Comment by abhinavkk** [comment]
Hey mate, was kind of planning to use this in an event I have on Thursday. If it works for you, can you do it until then? :)

**Comment by orahul1** [comment]
Sorry man. Too many changes than I expected.

**Comment by orahul1** [comment]
Fixed this issue. API endpoint changed to openweathermap
